version: "3"
services:
  web:
    container_name: mvc-app
    build:
      dockerfile: Dockerfile
      context: MvcApp
    ports:
      - "8090:80"
    environment:
      ConnectionStrings__ProductsContext: "Server=db;Database=ProductsContext;User=sa;Password=@Aa123456;"
    depends_on:
      - db

  db:
    container_name: mssql-db
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    expose:
      - "1433"
    environment:
      SA_PASSWORD: "@Aa123456"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
